### ISSUE TITLE
add custom `question` admonition 

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/2022.1-faes-tutorial#24]
I'm adding some admonition blocks through-out that pose questions to the user. I'm defining these as class question, but since that's not define they just show up as generic admonitions. We should define `question` as a custom admonition so we can style it different - for example, a question mark on the left side of the admonition box. 

I'm also using the `dropdown` class for these so the answer can be hidden from the user as they work through the tutorial. For example:

<img width="733" alt="Screen Shot 2021-12-20 at 6 28 27 PM" src="https://user-images.githubusercontent.com/192372/146855658-71291f44-23cc-4b35-ac0e-3caa999b2edc.png">

<img width="729" alt="Screen Shot 2021-12-20 at 6 28 52 PM" src="https://user-images.githubusercontent.com/192372/146855669-8f74d75b-2210-48fe-a90c-97440da7640c.png">

The source for this looks like the following:
`````
````{admonition} Try summarizing the feature table that was created by this round of filtering. Expand this box if you need help. 
:class: question, dropdown

```{usage}
use.action(
    use.UsageAction(plugin_id='feature_table', action_id='summarize'),
    use.UsageInputs(table=filtered_table_4, sample_metadata=sample_metadata),
    use.UsageOutputNames(visualization='filtered_table_4_summ'),
)
```
````
`````

One issue is that I don't think I can split the first line (the question) across multiple lines in the source or it will put the second and all remaining lines in the body of the admonition block rather than the header. If we could handle that with the custom admonition (if there isn't another way) that'd be pretty handy too.

**Comment by thermokarst** [comment]
What if we used this ebp extension, instead? https://ebp-sphinx-exercise.readthedocs.io/en/latest/syntax.html

**Comment by gregcaporaso** [comment]
Love it! :100:

**Comment by thermokarst** [comment]
Documenting here, a really easy way around the long-line issue in the admonition title is to use a JB substitution variable:

https://jupyterbook.org/content/content-blocks.html#substitutions-and-variables-in-markdown

![image](https://user-images.githubusercontent.com/274668/148831497-375e0434-7ba7-4e9f-abce-e5b3f15f5217.png)
![image](https://user-images.githubusercontent.com/274668/148831552-a2997910-a3dc-47f0-ac13-fd87c2da58c4.png)

**Comment by gregcaporaso** [comment]
Confirming that substitutions worked for the long-line issue - thanks @thermokarst!
