### ISSUE TITLE
Modify artifact numbering in feature table filtering tutorial

### ISSUE THREAD

**Issue by lina-kim** [gregcaporaso/2022.1-faes-tutorial#31]
The tutorial contains an [extraneous filtering step](https://gregcaporaso.github.io/2022.1-faes-tutorial/tutorial-1/07-filtering.html#perform-additional-filtering-steps-on-feature-table) after filtering for autoFMT study samples:

<img width="537" alt="Screenshot 2022-01-06 at 14 47 39" src="https://user-images.githubusercontent.com/25010133/148392808-eff827d0-f4b3-412a-a0a6-71cdc0ef2e87.png">

This step was removed in the video tutorial. Consequently, downstream artifact names are now off by 1, e.g. `filtered-table-1.qza` in the video corresponds to `filtered-table-2.qza` in the written tutorial. All references to these file names should be updated in the written tutorial.

**Comment by gregcaporaso** [comment]
Thanks @lina-kim! I'm making this change now.

**Comment by gregcaporaso** [comment]
Addressed in #38.
