### ISSUE TITLE
transfer upstream tutorial data from Dropbox to AWS

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/2022.1-faes-tutorial#35]
The data in the upstream tutorial (currently in PR #34) is stored in Dropbox - this should be transferred to the same location as the downstream data on AWS, and the link should be updated in the upstream tutorial. There is only one relevant file this time (`fastq-casava.zip`).

**Comment by Keegan-Evans** [comment]
https://github.com/qiime2/data302/pull/117
